// HISTORIAN — writes phase docs and the launch doc. Reports what happened.
// Does not speculate. Quotes evidence. Links runs by ID.
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { getDb, runs as runsTable, opportunities as oppTable, blockers as blockersTable } from "@autoresearcher/db";
import { eq, sql, desc } from "drizzle-orm";
import { callClaude, costCents, MODEL_SONNET } from "../lib/llm.js";
import { HISTORIAN_SYSTEM } from "@autoresearcher/skill";
import { startRun, finishRun } from "../lib/run-tracker.js";
import { publishEvent } from "../lib/pusher.js";

export const writePhaseDoc = async (phase: string): Promise<{ path: string }> => {
  const runId = await startRun({ phase: "ad-hoc", meta: { kind: "historian", phase } });
  let cost = 0n; let inT = 0n; let outT = 0n;
  try {
    const db = getDb();
    const phaseRuns = await db.query.runs.findMany({
      where: eq(runsTable.phase, phase as Parameters<typeof eq>[1] extends infer _ ? string : never as never),
    }).catch(async () => {
      // Fallback for non-enum phases
      return db.select().from(runsTable).where(sql`${runsTable.phase} = ${phase}`);
    });
    const opps = await db.select().from(oppTable).orderBy(desc(oppTable.scoreTotal)).limit(10);
    const opens = await db.select().from(blockersTable).where(sql`${blockersTable.resolvedAt} IS NULL`);

    const userJson = {
      phase,
      runs: phaseRuns.map((r) => ({
        id: r.id, status: r.status, startedAt: r.startedAt, finishedAt: r.finishedAt,
        usageCostCents: r.usageCostCents.toString(), error: r.errorMessage,
      })),
      topOpportunities: opps.map((o) => ({
        id: o.id, title: o.title, slug: o.verticalSlug, scoreTotal: o.scoreTotal,
      })),
      openBlockers: opens.map((b) => ({ kind: b.kind, filename: b.filename })),
    };

    const { text, inputTokens, outputTokens } = await callClaude({
      model: MODEL_SONNET,
      system: HISTORIAN_SYSTEM,
      userJson,
      maxTokens: 2048,
    });
    inT = BigInt(inputTokens); outT = BigInt(outputTokens);
    cost = costCents(MODEL_SONNET, inputTokens, outputTokens);

    const dir = "docs/runs";
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    const path = join(dir, `${phase}.md`);
    writeFileSync(path, `# ${phase}\n\nGenerated by HISTORIAN at ${new Date().toISOString()}.\n\n${text}\n`);

    await publishEvent("activity", {
      type: "phase_completed", phase, runId, at: new Date().toISOString(),
    }, runId);

    await finishRun({ runId, status: "completed", costCents: cost, inputTokens: inT, outputTokens: outT });
    return { path };
  } catch (err) {
    await finishRun({
      runId, status: "failed", costCents: cost, inputTokens: inT, outputTokens: outT,
      errorMessage: err instanceof Error ? err.message : String(err),
    });
    throw err;
  }
};

// Inflight status overwrites every 60 minutes per directive.
export const writeInflight = async (status: {
  finished: string[];
  inFlight: string[];
  evalScores: { tier: "A" | "B" | "C"; score: number }[];
  nextCheckpoint: string;
  liveDashboardUrl: string;
}): Promise<void> => {
  const dir = "docs/runs";
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  const text = `# _inflight\n\nUpdated: ${new Date().toISOString()}\n\n## Finished\n${status.finished.map((s) => `- ${s}`).join("\n") || "_none_"}\n\n## In flight\n${status.inFlight.map((s) => `- ${s}`).join("\n") || "_none_"}\n\n## Eval scores\n${status.evalScores.map((e) => `- Tier ${e.tier}: ${e.score}`).join("\n") || "_none_"}\n\n## Next checkpoint\n\n${status.nextCheckpoint}\n\n## Live dashboard\n\n${status.liveDashboardUrl}\n`;
  writeFileSync(join(dir, "_inflight.md"), text);
};
