-- Initial migration. Generated by hand to match schema/*.ts; in production this
-- file will be regenerated by `pnpm db:generate` and applied by `pnpm db:migrate`.
-- Per directive: NO destructive operations (drop / alter column) belong in this file.
-- If a future migration needs to drop a column it goes in a separate Tier-3
-- destructive migration that requires manual review.

CREATE TABLE IF NOT EXISTS `users` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `email` VARCHAR(320) NOT NULL,
  `name` VARCHAR(200),
  `is_operator` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_seen_at` TIMESTAMP NULL
);
CREATE INDEX `users_email_idx` ON `users` (`email`);

CREATE TABLE IF NOT EXISTS `runs` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `phase` ENUM('phase-0','phase-1','phase-2','phase-3','phase-4','phase-5','phase-6','scout-nightly','digest-weekly','eval-tier-a','eval-tier-b','eval-tier-c','ad-hoc') NOT NULL,
  `status` ENUM('queued','running','completed','failed','cancelled') NOT NULL DEFAULT 'queued',
  `started_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `finished_at` TIMESTAMP NULL,
  `usage_cost_cents` BIGINT NOT NULL DEFAULT 0,
  `input_tokens` BIGINT NOT NULL DEFAULT 0,
  `output_tokens` BIGINT NOT NULL DEFAULT 0,
  `error_message` TEXT,
  `parent_run_id` VARCHAR(36) NULL,
  `meta` JSON NOT NULL
);
CREATE INDEX `runs_phase_idx` ON `runs` (`phase`);
CREATE INDEX `runs_status_idx` ON `runs` (`status`);
CREATE INDEX `runs_parent_idx` ON `runs` (`parent_run_id`);
CREATE INDEX `runs_started_idx` ON `runs` (`started_at`);

CREATE TABLE IF NOT EXISTS `opportunities` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `run_id` VARCHAR(36) NOT NULL,
  `vertical_slug` VARCHAR(64) NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `thesis` TEXT NOT NULL,
  `evidence` JSON NOT NULL,
  `score_fit` INT NOT NULL,
  `score_evidence` INT NOT NULL,
  `score_market` INT NOT NULL,
  `score_competitive` INT NOT NULL,
  `score_founder` INT NOT NULL,
  `score_total` INT NOT NULL,
  `recommended_action` ENUM('deep-dive','interview-3-buyers','build-prototype','skip','watch') NOT NULL,
  `status` ENUM('inbox','reviewing','greenlit','rejected','stale') NOT NULL DEFAULT 'inbox',
  `greenlit_by_user_id` VARCHAR(36) NULL,
  `greenlit_at` TIMESTAMP NULL,
  `critic_verdict` ENUM('approve','reject','needs-revision') NULL,
  `critic_notes` TEXT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX `opp_vertical_idx` ON `opportunities` (`vertical_slug`);
CREATE INDEX `opp_status_idx` ON `opportunities` (`status`);
CREATE INDEX `opp_run_idx` ON `opportunities` (`run_id`);
CREATE INDEX `opp_score_idx` ON `opportunities` (`score_total`);
CREATE INDEX `opp_created_idx` ON `opportunities` (`created_at`);

CREATE TABLE IF NOT EXISTS `merges` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `pr_number` INT NOT NULL,
  `pr_title` VARCHAR(300) NOT NULL,
  `pr_url` VARCHAR(500) NOT NULL,
  `tier` ENUM('tier-1','tier-2','tier-3') NOT NULL,
  `status` ENUM('pending-cascade','ready-for-tap','merged','reverted','blocked') NOT NULL DEFAULT 'pending-cascade',
  `cascade_green` BOOLEAN NOT NULL DEFAULT FALSE,
  `critic_verdict` ENUM('approve','reject','needs-revision') NULL,
  `eval_delta_json` TEXT,
  `cost_cents` BIGINT NOT NULL DEFAULT 0,
  `safety_summary` TEXT,
  `merged_by_user_id` VARCHAR(36) NULL,
  `merged_at` TIMESTAMP NULL,
  `reverted_at` TIMESTAMP NULL,
  `revertable_until` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE INDEX `merges_pr_idx` ON `merges` (`pr_number`);
CREATE INDEX `merges_tier_idx` ON `merges` (`tier`);
CREATE INDEX `merges_status_idx` ON `merges` (`status`);

CREATE TABLE IF NOT EXISTS `blockers` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `kind` ENUM('material-ambiguity','missing-vercel-env','tier-c-regression','destructive-op','cost-ceiling','eval-gate-failure','out-of-allowlist','auto-action-refused','external-4xx','tier3-automerge-attempt','rate-ceiling','revert-failed','post-merge-sentry-spike','pusher-down') NOT NULL,
  `phase` VARCHAR(32) NOT NULL,
  `filename` VARCHAR(200) NOT NULL,
  `filed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `resolved_at` TIMESTAMP NULL,
  `failing_command_or_output` TEXT NOT NULL,
  `diagnosis` TEXT NOT NULL,
  `options` JSON NOT NULL,
  `default_after_24h` TEXT NOT NULL
);
CREATE INDEX `blockers_kind_idx` ON `blockers` (`kind`);
CREATE INDEX `blockers_phase_idx` ON `blockers` (`phase`);
CREATE INDEX `blockers_resolved_idx` ON `blockers` (`resolved_at`);

CREATE TABLE IF NOT EXISTS `events` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `type` VARCHAR(64) NOT NULL,
  `channel` VARCHAR(64) NOT NULL,
  `payload` JSON NOT NULL,
  `published_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `run_id` VARCHAR(36) NULL
);
CREATE INDEX `events_type_idx` ON `events` (`type`);
CREATE INDEX `events_channel_idx` ON `events` (`channel`);
CREATE INDEX `events_published_idx` ON `events` (`published_at`);
CREATE INDEX `events_run_idx` ON `events` (`run_id`);

CREATE TABLE IF NOT EXISTS `magic_links` (
  `id` VARCHAR(36) NOT NULL PRIMARY KEY,
  `token_hash` VARCHAR(128) NOT NULL UNIQUE,
  `purpose` VARCHAR(32) NOT NULL,
  `subject_id` VARCHAR(36) NOT NULL,
  `user_id` VARCHAR(36) NOT NULL,
  `expires_at` TIMESTAMP NOT NULL,
  `consumed_at` TIMESTAMP NULL,
  `revoked` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX `magic_purpose_subject_idx` ON `magic_links` (`purpose`, `subject_id`);
CREATE INDEX `magic_expires_idx` ON `magic_links` (`expires_at`);
