// Embedded fallback for the skill library. The .md files in
// packages/learn/fixtures/skills/ are still the authoritative editable
// source; this module is regenerated by `pnpm gen:skills` (see
// scripts/gen-skills.mjs) whenever those files change.
//
// Why exist at all: Next.js' outputFileTracing doesn't reliably bundle
// arbitrary fixture files for serverless functions. Embedding the data
// guarantees skills are available at runtime on Vercel without runtime
// FS lookups.

import type { Skill } from "../skills.js";

export const EMBEDDED_SKILLS: Skill[] = [
  {
    id: "named-buyer-floor",
    when: "a finding doesn't name a specific buyer or a specific budget owner",
    verticals: [],
    priority: 5,
    body:
      "Refuse to emit any finding whose evidence does not name at least one\n" +
      "concrete buyer (a person with a title, or a specific company department\n" +
      "with budget authority). \"SMBs are frustrated with X\" is not a buyer.\n" +
      "\"Loan officers at IMBs with $50M+ originations\" is. If you cannot find\n" +
      "a named-buyer signal in the evidence, log it and skip — do not\n" +
      "hallucinate a buyer to fill the slot.",
    filename: "named-buyer-floor.md",
  },
  {
    id: "two-domain-evidence",
    when: "building the evidence array",
    verticals: [],
    priority: 5,
    body:
      "Every emitted finding must cite at least two URLs from two distinct\n" +
      "domains. Same-domain confirmation (e.g., two pages on the vendor's own\n" +
      "site) is not independent evidence. If you only find single-domain\n" +
      "sources, mark `evidenceQuality` low and prefer to skip than to emit.",
    filename: "two-domain-evidence.md",
  },
  {
    id: "mortgage-cycle-time",
    when: "scoping mortgage-origination findings",
    verticals: ["mortgage-origination-internal", "lo-processor-productivity"],
    priority: 4,
    body:
      "For mortgage findings, frame the wedge in terms of cycle-time impact\n" +
      "(days-to-close, conditions-cleared-per-LO-week) or compliance-load\n" +
      "impact (audit findings closed, exam-prep hours), not \"AI\" generally.\n" +
      "A loan officer reading the digest cares about closing more loans this\n" +
      "month, not about model architectures.",
    filename: "mortgage-cycle-time.md",
  },
  {
    id: "compliance-named-rule",
    when: "the finding involves regulation or compliance",
    verticals: ["compliance-ops-licensed-financial", "b2b-compliance-audit"],
    priority: 4,
    body:
      "Compliance findings must cite the specific rule, statute, or framework\n" +
      "clause being addressed (e.g., \"12 CFR Part 1024.41 loss mitigation\",\n" +
      "\"SOC 2 CC6.1 logical access\"). Compliance buyers do not buy from\n" +
      "vendors who don't know the rule numbers. If the evidence doesn't pin a\n" +
      "specific rule, mark `fit` low.",
    filename: "compliance-named-rule.md",
  },
  {
    id: "dev-tools-distribution",
    when: "scoring developer-tools findings",
    verticals: ["developer-tools"],
    priority: 4,
    body:
      "Developer tools have a hard distribution problem; scoring should weight\n" +
      "\"founder edge in distribution\" (existing audience, GitHub presence,\n" +
      "open-source track record, conference speaking) over generic technical\n" +
      "talent. A novel devtool with no distribution path scores `competitiveDensity`\n" +
      "high (saturated) and `marketSize` low (niche), even if the idea is good.",
    filename: "dev-tools-distribution.md",
  },
];
